### PR TITLE
Added Sub-Admin Verification

### PR DESCRIPTION
**Pull request by TheRightGift**

### CODE REVIEW

**Comment by david-saint** [comment]
It has conflicts

**Comment by TheRightGift** [comment]
Resolved the conflict

**Comment by TheRightGift** [comment]
Some routes i need for the Admin panel re not accessible. They are accessible on my local server. Please can you make them accessible. 
They include:
/api/v1/user/users, /api/v1/user/clinics, /api/v1/user/global

**Comment by david-saint** [comment]
Those routes require a user to be logged in to access... you'll have to reimplement the endpoints you need in `rooutes/api/v1/admin.php`

Make sure you also protect that one with a middleware that requires an admin to be logged in

**Comment by david-saint** [comment]
Looking at it again.. it seems you didn't make those endpoints protected...
That means anybody can call the endpoint and get all our users... that is very very bad

**Pull request merged**
